Repository withPet-team/withPet-client, pull requests merged in 2023-03, with the labels that each got.

#65 [❇️] Feature Header Component & Navigation Bar Component
  withpet/src/assets/sprites_icon.png
  withpet/src/components/App/App.tsx
  withpet/src/components/Header/Header.tsx
  withpet/src/components/Navigation/Navigation.tsx
  withpet/src/components/SignUp/SignUp.tsx
  withpet/src/firebase-config.js
  withpet/src/index.tsx
  withpet/tailwind.config.js
  withpet/tsconfig.json
Labels: ❇️ Feature

#72 [❇️] Feature Welcome & Sign In
  withpet/package-lock.json
  withpet/package.json
  withpet/src/components/App/App.tsx
  withpet/src/components/SignIn/AlreadySignIn.tsx
  withpet/src/components/SignIn/SignInInput.tsx
  withpet/src/components/SignIn/SignInLink.tsx
  withpet/src/components/SignIn/SocialIcon.tsx
  withpet/src/components/SignIn/SocialLogin.tsx
  withpet/src/components/UI/Container.tsx
  withpet/src/components/UI/CustomModal.tsx
  withpet/src/components/UI/LinkButton.tsx
  withpet/src/components/Welcome/WelcomeBtn.tsx
  withpet/src/firebase-config.js
  withpet/src/redux/auth-slice.tsx
  withpet/src/redux/store.jsx
  withpet/src/redux/store.tsx
  withpet/src/router/SignIn.tsx
  withpet/src/router/Welcome.tsx
  withpet/tailwind.config.js
Labels: ❇️ Feature

#73 [🔧] Change SignUp Directory
  withpet/src/router/SignUp.tsx
Labels: 🔧 Chore

#78 [💄] 컨텐츠 잘림 현상 수정
  withpet/src/components/Header/Header.tsx
  withpet/src/components/UI/Container.tsx
  withpet/src/router/Diary.tsx
Labels: 💄 Style

#87 [💄] Apply the navigation bar only to the paths needed
  withpet/src/components/Navigation/Navigation.tsx
Labels: 💄 Style

#90 [✨] 로그인 유지 방식 변경 & Story 페이지 카드 컴포넌트 일부 마크업 및 스타일링(ing)
  withpet/package-lock.json
  withpet/package.json
  withpet/src/assets/sprites_icon.png
  withpet/src/assets/제목 없음-1.png
  withpet/src/components/App/App.tsx
  withpet/src/components/SignIn/SocialIcon.tsx
  withpet/src/components/Story/StoryCard.tsx
  withpet/src/components/Story/StoryContent.tsx
  withpet/src/components/Story/StoryImage.tsx
  withpet/src/components/Story/StoryWriter.tsx
  withpet/src/components/Story/SubBtn.tsx
  withpet/src/firebase-config.js
  withpet/src/redux/store.tsx
  withpet/src/router/AlreadySignIn.tsx
  withpet/src/router/PrivateRoute.tsx
  withpet/src/router/SignIn.tsx
  withpet/src/router/SignUp.tsx
  withpet/src/router/Story.tsx
  withpet/tailwind.config.js
Labels: ❇️ Feature

#103 [❇️] 카드컴포넌트 DB 정보 받아와 렌더링 기능 추가
  withpet/src/components/Diary/SubmitDiary.tsx
  withpet/src/components/Diary/WeatherChoose.tsx
  withpet/src/components/Story/StoryCard.tsx
  withpet/src/components/Story/StoryComment.tsx
  withpet/src/components/Story/StoryContent.tsx
  withpet/src/components/Story/StoryImage.tsx
  withpet/src/components/Story/StoryWriter.tsx
  withpet/src/components/Story/SubBtn.tsx
  withpet/src/router/Story.tsx
Labels: ❇️ Feature

#105 [🐞] Fix Header Component
  withpet/src/assets/sprites_icon.png
  withpet/src/components/Diary/SubmitDiary.tsx
  withpet/src/components/Header/Header.tsx
Labels: 🐞 Fix, 💄 Style, 🔨 Refactor

#106 [🐞] Fix Sprites Icon Direction
  withpet/src/components/Diary/WeatherChoose.tsx
  withpet/src/components/Navigation/Navigation.tsx
  withpet/src/components/Story/StoryWriter.tsx
Labels: 🐞 Fix

#108 [🔨] Refactoring Navigation Bar
  withpet/src/components/Navigation/Navigation.tsx
Labels: 🔨 Refactor

#117 [🔨] PetInfo 리팩토링, submit 시 storage에 사진 저장
  withpet/src/components/PetInfo/PetInfoForm.tsx
  withpet/src/components/PetInfo/PetInfoImg.tsx
  withpet/src/redux/slice/petInfo/petInfoSlice.tsx
Labels: 🔨 Refactor

#119 [✨] PetInfo 수정/삭제 후 초기화 및 조건처리 & MyPage 수정 버튼 및 캘린더에 다이어리 데이터 렌더링
  withpet/src/components/MyPage/MyPageCalendar.tsx
  withpet/src/components/MyPage/MyPageEditBtn.tsx
  withpet/src/components/MyPage/MyPageMyPet.tsx
  withpet/src/components/PetInfo/PetInfoForm.tsx
  withpet/src/components/PetInfo/PetInfoModifyAndDelete.tsx
  withpet/src/redux/slice/petInfo/petInfoSlice.tsx
  withpet/src/router/PetInfo.tsx
Labels: ❇️ Feature, 🔨 Refactor

#120 [💄] Complete SignUp Page
  withpet/src/components/SignIn/SocialIcon.tsx
  withpet/src/components/SignUp/SignUpInput.tsx
  withpet/src/router/SignUp.tsx
Labels: 🐞 Fix, 💄 Style, 🔨 Refactor

#124 [❇️] Feature Setting Page
  withpet/src/components/App/App.tsx
  withpet/src/components/Setting/AppInfo.tsx
  withpet/src/components/Setting/ChangeProfile.tsx
  withpet/src/components/Setting/DarkMode.tsx
  withpet/src/components/Setting/LogOutBtn.tsx
  withpet/src/components/Setting/Notice.tsx
  withpet/src/components/Setting/UnsubscribingBtn.tsx
  withpet/src/router/Setting.tsx
  withpet/src/router/SignUp.tsx
  withpet/tailwind.config.js
Labels: ❇️ Feature

#125 [✨] PetInfo 수정/삭제
  withpet/src/components/PetInfo/PetInfoForm.tsx
  withpet/src/components/PetInfo/PetInfoImg.tsx
  withpet/src/components/PetInfo/PetInfoModifyAndDelete.tsx
  withpet/src/components/PetInfo/PetInfoRadioBtn.tsx
  withpet/src/redux/slice/petInfo/petInfoSlice.tsx
Labels: ❇️ Feature, 🔨 Refactor

#130 [🔨] MyPage, PetInfo 리팩토링
  withpet/src/components/MyPage/MyPageCalendar.tsx
  withpet/src/components/PetInfo/PetInfoImg.tsx
  withpet/src/components/PetInfo/PetInfoInput.tsx
  withpet/src/components/PetInfo/PetInfoModifyAndDelete.tsx
  withpet/src/components/PetInfo/PetInfoRadioBtn.tsx
  withpet/src/components/PetInfo/PetInfoRadioGroup.tsx
  withpet/src/router/PetInfo.tsx
Labels: 🔨 Refactor

#132 [❇️] 댓글 불러오는 코드 리팩토링 & 댓글 수정 삭제 기능 추가
  withpet/src/components/MyPage/MyPageCalendar.tsx
  withpet/src/components/SignIn/SocialIcon.tsx
  withpet/src/components/Story/Comment.tsx
  withpet/src/components/Story/CommentWrap.tsx
  withpet/src/components/Story/StoryCard.tsx
  withpet/src/components/Story/SubBtn.tsx
  withpet/src/components/Story/WriteComment.tsx
  withpet/src/router/DiaryComments.tsx
  withpet/src/router/Story.tsx
Labels: ❇️ Feature, 🐞 Fix

#129 [💄] 회원가입 링크 연결 수정 및 세팅 링크 연결
  withpet/src/components/Header/Header.tsx
  withpet/src/components/Navigation/Navigation.tsx
  withpet/src/components/Setting/ChangeProfile.tsx
  withpet/src/components/Setting/DarkMode.tsx
  withpet/src/components/Setting/Notice.tsx
  withpet/src/components/Setting/UnsubscribingBtn.tsx
  withpet/src/router/Setting.tsx
  withpet/src/router/SignUp.tsx
  withpet/tailwind.config.js
Labels: 🐞 Fix, 💄 Style

#137 [❇️/💄] Feature/Style Seacrh Page
  withpet/package-lock.json
  withpet/package.json
  withpet/src/router/Chatting.jsx
  withpet/src/router/Chatting.tsx
Labels: ❇️ Feature, 💄 Style

#141 [💄] Style Search Page
  withpet/src/router/Chatting.jsx
Labels: 💄 Style

#145 [🔨] 불필요한 코드 삭제
  withpet/src/router/Chatting.jsx
  withpet/src/router/SignUp.tsx
Labels: 🔨 Refactor
